### ISSUE TITLE
HTML to PDF functionality

### ISSUE THREAD

**Issue by fma-technologies** [fma-technologies/fma-wiki-to-pdf#4]
This will probably be the hardest part of the project, so until we figure out how to achieve it maybe we can just spitball some ideas,

The first one is https://github.com/Microsoft/DesktopBridgeToUWP-Samples/tree/master/Samples/AppServiceBridgeSample/cs - Microsoft give an example of how to have a bridge between UWP apps and classic Windows apps. So maybe we can use an wkhtmltopdf wrapper on a classic Windows app, and then use the bridge to send the data to it?

---

Maybe https://github.com/ArthurHub/HTML-Renderer ??

> Create PDF document from HTML code snippets.

---

https://msdn.microsoft.com/en-us/library/windows/apps/windows.data.pdf.aspx?f=255&MSPPError=-2147217396

---

Print from webview?
https://msdn.microsoft.com/en-us/windows/uwp/devices-sensors/print-from-your-app#create-a-print-button

**Comment by tawazz** [comment]
printing pages inside scrollview
http://stackoverflow.com/questions/17049677/how-do-i-print-webview-content-in-a-windows-store-app

**Comment by fma-technologies** [comment]
Brokered components
https://visualstudiogallery.msdn.microsoft.com/527286e4-b06a-4234-adde-d313c9c3c23e

**Comment by fma-technologies** [comment]
I feel like I'm swimming against the tide a bit here but slowly we are getting closer to making PDF printing a reality. After lots of mucking around I got the code from the Stackoverflow you linked to working:

![ss1j45](https://cloud.githubusercontent.com/assets/5977709/17800554/be035e80-6616-11e6-81e5-16be3b49c16f.png)

It's all on the `print-to-pdf` branch.

So now we have a bunch of rectangles/webbrushviews that maybe we can print? I haven't got any idea how we get to that step though.

http://cheahengsoon.weebly.com/blog/uwp-using-the-printer-api could be useful.

**Comment by fma-technologies** [comment]
One step closer.
It now displays the print dialog... it totally crashes after a second, but it's another step in the right direction. I think the problem is we need to pass in the Rectangles better... it seems to be thinking page is `null` an awful lot in `protected virtual RichTextBlockOverflow AddOnePrintPreviewPage(RichTextBlockOverflow lastRTBOAdded, PrintPageDescription printPageDescription)`. That whole RichTextBlock thing might be a problem too. I don't know at this point, but it's progress.

![ss1j45](https://cloud.githubusercontent.com/assets/5977709/17849449/6524ed66-688b-11e6-9cc4-483a762cc0c2.png)

**Comment by fma-technologies** [comment]
Good news @tawazz - the code on the `print-to-pdf` branch now *actually* prints to PDF!
The dimensions are totally wrong and the print preview only half works, and the "Save" UI looks totally weird... but even though it still needs work, we can now say that the wiki converts to PDF!

Here's an example PDF, it looks pretty funny but at least it's a real PDF that generates without exception messages! 

* [test2.pdf](https://github.com/fma-technologies/fma-wiki-to-pdf/files/431916/test2.pdf)
