### ISSUE TITLE
Load files

### ISSUE THREAD

**Issue by fma-technologies** [fma-technologies/fma-wiki-to-pdf#5]
Load files from:

* [x] Local directory
* [x] Git repo
    * [x] Need to figure out -- how can we grab from a git repo in UWP? [yes we can]
    * [x] Need to figure out if it's viable to include private repos [yes it is, prompts for auth]
    * [x] How to store the files? Temp directory?

**Comment by fma-technologies** [comment]
It's looking likely that we'll be able to access remote files from GitHub fortunately. We will be limited in terms of where the files go (`C:\Users\xxxx\AppData\Local\Packages\yyyy\LocalState`), but that's okay. It might even work out, we could temporarily move the local files to the same place to avoid storing them in memory. Or we could store the Git files in memory, either could work.

**Comment by tawazz** [comment]
![capture](https://cloud.githubusercontent.com/assets/12362544/17724576/ce4e07ec-6475-11e6-9db3-c368113f8061.PNG)

- maybe give the remote folder a random generated name, I don't think we have delete permissions

**Comment by fma-technologies** [comment]
That's weird! And that is using my latest changes too...
Let me know what steps you took to get that error, and I'll try and reproduce it on my machine.
