### ISSUE TITLE
Convert To Html

### ISSUE THREAD

**Issue by tawazz** [fma-technologies/fma-wiki-to-pdf#7]
- [x] Add validation logic

- [x] convert md files to html

- [x] add converted html to theme files

- [x] save the html document to location on disk

**Comment by fma-technologies** [comment]
Hopefully we think of something for https://github.com/fma-technologies/fma-wiki-to-pdf/issues/4! I've been reading into AppServices, I think that might be our best bet at the moment.

And for the git functionality, maybe https://github.com/anhoavu/LibGit2-UWP-WinRT-Component
