### ISSUE TITLE
Clear all values

### ISSUE THREAD

**Issue by fma-technologies** [fma-technologies/fma-wiki-to-pdf#8]
Have some kind of reset button that will:

* Clear the selected theme
* Clear cover page values
* Clear file list

As part of this, see if there is some way - on app launch - to delete the temp folders in the `C:\Users\xyz\AppData\Local\Packages\acfbe6b9-7a95-4d7c-aa03-7206b2187dc0_e3aaj5f6nvr22\LocalState` directory.

**Comment by tawazz** [comment]
link to icons
https://msdn.microsoft.com/en-us/windows/uwp/style/segoe-ui-symbol-font#symbol-enumeration
